"""Repository onboarding used by the public ``watchmyai`` release commands.

The installed gateway remains usable as a standalone wheel.  These helpers are
activated only when the release repository is present, because setup, rule
installation, and live detection validation intentionally consume reviewed
repository assets.
"""

from __future__ import annotations

import base64
import getpass
import json
import os
import platform
import shutil
import socket
import ssl
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from watchmyai.gateway import Gateway, GatewayConfig

EXIT_CONFIGURATION = 3
EXIT_CONNECTIVITY = 4
EXIT_RULE_IMPORT = 5
EXIT_VALIDATION = 6


class OnboardingError(RuntimeError):
    """An operator-facing onboarding failure with no secret-bearing detail."""

    def __init__(self, message: str, *, exit_code: int = EXIT_VALIDATION):
        super().__init__(message)
        self.exit_code = exit_code


@dataclass(frozen=True)
class Stage:
    name: str
    status: str
    detail: str


def repository_root() -> Path:
    configured = os.environ.get("WATCHMYAI_REPOSITORY", "").strip()
    candidates = [Path(configured).expanduser()] if configured else []
    candidates.extend(Path(__file__).resolve().parents)
    cwd = Path.cwd().resolve()
    candidates.extend((cwd, *cwd.parents))
    for candidate in candidates:
        if (
            (candidate / ".env.example").is_file()
            and (candidate / "scripts/preflight.py").is_file()
            and (candidate / "deployment/rules_schema_1.1.0.ndjson").is_file()
        ):
            return candidate.resolve()
    raise OnboardingError(
        "release repository not found; run this command from a WatchMyAI clone or set WATCHMYAI_REPOSITORY"
    )


def _read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for number, raw in enumerate(path.read_text("utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise OnboardingError(f"{path}:{number}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        if not key or not key.replace("_", "").isalnum() or not key[0].isalpha():
            raise OnboardingError(f"{path}:{number}: invalid configuration key")
        if key in values:
            raise OnboardingError(f"{path}:{number}: duplicate configuration key {key}")
        values[key] = value.strip().strip('"').strip("'")
    return values


def _write_private(path: Path, content: str) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.replace(path)
        if os.name != "nt":
            path.chmod(0o600)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def _backup_existing(path: Path) -> Path | None:
    if not path.exists():
        return None
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%S%fZ")
    backup = path.with_name(f"{path.name}.wmai-backup-{stamp}")
    shutil.copy2(path, backup)
    return backup


def _write_config(path: Path, template: dict[str, str], values: dict[str, str]) -> None:
    lines = [
        "# Generated by watchmyai setup. Re-run setup to make reviewed changes.",
        "# Credentials are referenced through owner-only files where supported.",
    ]
    for key in template:
        value = values.get(key, "")
        if "\n" in value or "\r" in value:
            raise OnboardingError(f"{key} contains a newline")
        lines.append(f"{key}={value}")
    for key in sorted(set(values) - set(template)):
        value = values[key]
        if "\n" in value or "\r" in value:
            raise OnboardingError(f"{key} contains a newline")
        lines.append(f"{key}={value}")
    content = "\n".join(lines) + "\n"
    if path.exists() and path.read_text("utf-8") == content:
        return
    _backup_existing(path)
    _write_private(path, content)


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str] | None = None,
    timeout: int = 900,
) -> Stage:
    completed = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )
    output = (completed.stdout + completed.stderr).strip()
    return Stage(
        " ".join(command),
        "PASS" if completed.returncode == 0 else "FAIL",
        output[-4000:],
    )


def _require(stage: Stage, *, code: int) -> None:
    label = stage.name
    if stage.status == "PASS":
        print(f"[PASS] {label}")
        if stage.detail:
            print(stage.detail)
        return
    if stage.detail:
        print(stage.detail, file=sys.stderr)
    raise OnboardingError(f"stage failed: {label}", exit_code=code)


def _environment(values: dict[str, str]) -> dict[str, str]:
    environment = dict(os.environ)
    for key, value in values.items():
        environment.setdefault(key, value)
    if values.get("ELASTICSEARCH_URL"):
        environment.setdefault("ELASTIC_URL", values["ELASTICSEARCH_URL"])
    return environment


def _prompt(label: str, current: str = "", *, secret: bool = False) -> str:
    suffix = f" [{current}]" if current else ""
    reader = getpass.getpass if secret else input
    entered = reader(f"{label}{suffix}: ").strip()
    return entered or current


def _materialize_api_key(values: dict[str, str], home: Path) -> None:
    if values.get("ELASTIC_AUTH_METHOD", "api_key") != "api_key":
        return
    key_file = values.get("ELASTIC_API_KEY_FILE", "").strip()
    raw_key = os.environ.get("ELASTIC_API_KEY", "").strip() or values.get("ELASTIC_API_KEY", "").strip()
    if "__SET_ME__" in raw_key:
        raw_key = ""
    if raw_key:
        target = home / "secrets" / "elastic-api-key"
        _write_private(target, raw_key + "\n")
        values["ELASTIC_API_KEY"] = ""
        values["ELASTIC_API_KEY_FILE"] = str(target)
    elif key_file:
        values["ELASTIC_API_KEY_FILE"] = str(Path(key_file).expanduser().resolve())


def _collect_configuration(args: Any, root: Path) -> tuple[Path, dict[str, str]]:
    template_path = root / ".env.example"
    template = _read_env(template_path)
    config_path = Path(args.config).expanduser().resolve()
    values = dict(template)
    if config_path.is_file():
        values.update(_read_env(config_path))
    for key in template:
        supplied = os.environ.get(key)
        if supplied is not None and supplied != "":
            values[key] = supplied

    option_map = {
        "WATCHMYAI_HOME": getattr(args, "home", None),
        "ELASTICSEARCH_URL": getattr(args, "elastic_url", None),
        "KIBANA_URL": getattr(args, "kibana_url", None),
        "FLEET_SERVER_URL": getattr(args, "fleet_url", None),
        "ELASTIC_API_KEY_FILE": getattr(args, "api_key_file", None),
        "ELASTIC_AGENT_PATH": getattr(args, "elastic_agent_path", None),
        "FLEET_AGENT_POLICY_ID": getattr(args, "fleet_policy_id", None),
    }
    for key, value in option_map.items():
        if value:
            values[key] = str(value)

    for key in (
        "ELASTIC_API_KEY",
        "ELASTIC_API_KEY_FILE",
        "ELASTIC_CA_CERT",
        "FLEET_CA_CERT",
        "ELASTIC_AGENT_PATH",
    ):
        if "__SET_ME__" in values.get(key, ""):
            values[key] = ""

    home_value = values.get("WATCHMYAI_HOME", "")
    if not home_value or "__SET_ME__" in home_value or home_value == "/var/lib/watchmyai":
        home_value = str(Path.home() / ".local" / "state" / "watchmyai")
    home = Path(home_value).expanduser().resolve()
    values.update(
        {
            "WATCHMYAI_MACHINE_ROLE": "ubuntu-server",
            "WATCHMYAI_HOME": str(home),
            "WATCHMYAI_DATASET": "watchmyai.events",
            "SOURCE_DATA_STREAM": "logs-watchmyai.events-*",
            "ALERT_INDEX_PATTERN": ".alerts-security.alerts-*",
            "WATCHMYAI_TEST_WORKSPACE": str(home / "validation-workspace"),
            "WATCHMYAI_LAB_MODE": "true" if args.development else "false",
            "ENABLE_RULES": "true" if args.development else "false",
        }
    )
    if args.enable_rules is not None:
        values["ENABLE_RULES"] = "true" if args.enable_rules else "false"
    if args.development:
        values["WATCHMYAI_POLICY_MODE"] = "development"
    else:
        values["WATCHMYAI_POLICY_MODE"] = "signed"

    required_prompts = (
        ("ELASTICSEARCH_URL", "Elasticsearch URL"),
        ("KIBANA_URL", "Kibana URL"),
        ("FLEET_SERVER_URL", "Fleet Server URL"),
    )
    for key, label in required_prompts:
        current = values.get(key, "")
        if "__SET_ME__" in current:
            current = ""
        if not current and not args.non_interactive:
            current = _prompt(label)
        values[key] = current

    _materialize_api_key(values, home)
    if values.get("ELASTIC_AUTH_METHOD", "api_key") == "api_key":
        if not values.get("ELASTIC_API_KEY_FILE") and not args.non_interactive:
            raw_key = _prompt("Elastic API key", secret=True)
            if raw_key:
                target = home / "secrets" / "elastic-api-key"
                _write_private(target, raw_key + "\n")
                values["ELASTIC_API_KEY_FILE"] = str(target)
                values["ELASTIC_API_KEY"] = ""

    if not values.get("ELASTIC_AGENT_PATH"):
        candidates = [
            Path(shutil.which("elastic-agent") or ""),
            Path("/opt/Elastic/Agent/elastic-agent"),
            Path("/usr/bin/elastic-agent"),
        ]
        detected = next((path for path in candidates if path.is_file()), None)
        if detected is not None:
            values["ELASTIC_AGENT_PATH"] = str(detected.resolve())

    unresolved = [
        key
        for key in ("ELASTICSEARCH_URL", "KIBANA_URL", "FLEET_SERVER_URL")
        if not values.get(key) or "__SET_ME__" in values[key]
    ]
    if values.get("ELASTIC_AUTH_METHOD", "api_key") == "api_key" and not (
        values.get("ELASTIC_API_KEY") or values.get("ELASTIC_API_KEY_FILE")
    ):
        unresolved.append("ELASTIC_API_KEY or ELASTIC_API_KEY_FILE")
    if unresolved:
        raise OnboardingError(
            "missing setup values: "
            + ", ".join(unresolved)
            + "; provide environment variables or rerun interactively",
            exit_code=EXIT_CONFIGURATION,
        )

    Path(values["WATCHMYAI_TEST_WORKSPACE"]).mkdir(mode=0o700, parents=True, exist_ok=True)
    _write_config(config_path, template, values)
    return config_path, values


def _write_gateway_environment(home: Path, values: dict[str, str]) -> Path:
    keys = (
        "ELASTICSEARCH_URL",
        "ELASTIC_URL",
        "ELASTIC_AUTH_METHOD",
        "ELASTIC_API_KEY_FILE",
        "ELASTIC_USERNAME",
        "ELASTIC_PASSWORD",
        "TLS_VERIFY",
        "ELASTIC_CA_CERT",
        "WATCHMYAI_DATASET",
        "SOURCE_DATA_STREAM",
    )
    payload = dict(values)
    payload["ELASTIC_URL"] = values["ELASTICSEARCH_URL"]
    path = home / "gateway.env"
    _write_private(path, "".join(f"{key}={payload.get(key, '')}\n" for key in keys))
    return path


def _configure_gateway(
    home: Path,
    values: dict[str, str],
    *,
    development: bool,
    repository_only: bool,
) -> None:
    config = GatewayConfig.load(home)
    raw = yaml.safe_load(config.config_path.read_text("utf-8")) or {}
    output = raw.setdefault("output", {})
    if repository_only:
        output["mode"] = "jsonl"
    else:
        gateway_environment = _write_gateway_environment(home, values)
        output["mode"] = "elastic"
        output["elastic"] = {"environment_file": str(gateway_environment)}
    enforcement = raw.setdefault("enforcement", {})
    enforcement["allow_unsigned_policy"] = development
    enforcement["unsigned_policy_bundle"] = str(config.unsigned_policy_bundle)
    header = (
        "# Generated by watchmyai setup. Credentials remain in owner-only files.\n"
        "# Re-run setup instead of hand-editing this file.\n"
    )
    _write_private(config.config_path, header + yaml.safe_dump(raw, sort_keys=False))
    if development:
        policy = yaml.safe_load(config.unsigned_policy_bundle.read_text("utf-8"))
        policy["organization_id"] = "watchmyai-development"
        policy["metadata"]["approved_workspace_roots"] = [values["WATCHMYAI_TEST_WORKSPACE"]]
        _write_private(
            config.unsigned_policy_bundle,
            "# Generated safe development policy; unsigned use is explicit in config.yml.\n"
            + yaml.safe_dump(policy, sort_keys=False),
        )


class FleetClient:
    """Small fail-closed client for the Fleet APIs needed by setup and verify."""

    def __init__(self, values: dict[str, str]):
        kibana_url = values["KIBANA_URL"].rstrip("/")
        parsed = urllib.parse.urlparse(kibana_url)
        loopback = parsed.hostname in {"127.0.0.1", "::1", "localhost"}
        if (
            not parsed.hostname
            or parsed.username
            or parsed.password
            or parsed.scheme not in ({"http", "https"} if loopback else {"https"})
        ):
            raise OnboardingError(
                "KIBANA_URL must be credential-free HTTPS (HTTP is allowed only on loopback)",
                exit_code=EXIT_CONFIGURATION,
            )
        space = values.get("KIBANA_SPACE", "default")
        prefix = "" if space == "default" else f"/s/{urllib.parse.quote(space, safe='')}"
        self.base = kibana_url + prefix
        self.headers = {"Accept": "application/json", "kbn-xsrf": "watchmyai-setup"}
        method = values.get("ELASTIC_AUTH_METHOD", "api_key")
        if method == "api_key":
            key = values.get("ELASTIC_API_KEY", "")
            key_file = values.get("ELASTIC_API_KEY_FILE", "")
            if not key and key_file:
                key = Path(key_file).expanduser().read_text("utf-8").strip()
            if not key:
                raise OnboardingError("Fleet API key is unavailable", exit_code=EXIT_CONFIGURATION)
            self.headers["Authorization"] = f"ApiKey {key}"
        else:
            token = base64.b64encode(
                f"{values.get('ELASTIC_USERNAME', '')}:{values.get('ELASTIC_PASSWORD', '')}".encode()
            ).decode("ascii")
            self.headers["Authorization"] = f"Basic {token}"
        verify = values.get("TLS_VERIFY", "true").lower() == "true"
        if not verify and not loopback:
            raise OnboardingError(
                "TLS_VERIFY=false is allowed only for loopback services",
                exit_code=EXIT_CONFIGURATION,
            )
        ca_file = values.get("ELASTIC_CA_CERT", "")
        self.context = (
            ssl.create_default_context(cafile=ca_file)
            if verify and ca_file
            else ssl.create_default_context()
            if verify
            # Insecure contexts are reachable only for explicitly selected loopback URLs.
            else ssl._create_unverified_context()  # nosec B323
        )

    def request(
        self, path: str, *, method: str = "GET", body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        headers = dict(self.headers)
        data = None
        if body is not None:
            headers["Content-Type"] = "application/json"
            data = json.dumps(body).encode()
        request = urllib.request.Request(
            self.base + path,
            data=data,
            headers=headers,
            method=method,
        )
        try:
            # The base scheme and host are constrained above before this opener is reached.
            with urllib.request.urlopen(  # nosec B310
                request, timeout=30, context=self.context
            ) as response:
                return json.loads(response.read() or b"{}")
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", "replace")[:500]
            raise OnboardingError(
                f"Fleet API {method} {path} returned HTTP {exc.code}: {detail}",
                exit_code=EXIT_CONNECTIVITY,
            ) from exc
        except (urllib.error.URLError, TimeoutError, OSError) as exc:
            raise OnboardingError(
                f"Fleet API {method} {path} failed: {exc}",
                exit_code=EXIT_CONNECTIVITY,
            ) from exc

    @staticmethod
    def _agent_hostnames(agent: dict[str, Any]) -> set[str]:
        names: set[str] = set()
        for branch in (agent.get("local_metadata", {}), agent.get("user_provided_metadata", {})):
            host = branch.get("host", {}) if isinstance(branch, dict) else {}
            if isinstance(host, dict):
                names.update(str(host.get(key, "")) for key in ("hostname", "name") if host.get(key))
        return names

    def select_policy(self, configured: str, *, interactive: bool) -> str:
        policies = self.request("/api/fleet/agent_policies?perPage=100").get("items", [])
        policy_ids = {str(item.get("id")): str(item.get("name", "")) for item in policies}
        if configured:
            if configured not in policy_ids:
                raise OnboardingError(f"FLEET_AGENT_POLICY_ID does not exist: {configured}")
            return configured
        agents = self.request("/api/fleet/agents?perPage=100&showInactive=false").get("items", [])
        local_names = {socket.gethostname(), platform.node()}
        matches = {
            str(agent.get("policy_id"))
            for agent in agents
            if str(agent.get("status", "")).lower() in {"online", "healthy"}
            and self._agent_hostnames(agent) & local_names
            and agent.get("policy_id")
        }
        if len(matches) == 1:
            return matches.pop()
        online_policies = {
            str(agent.get("policy_id"))
            for agent in agents
            if str(agent.get("status", "")).lower() in {"online", "healthy"} and agent.get("policy_id")
        }
        if len(online_policies) == 1:
            return online_policies.pop()
        if interactive and policies:
            print("Fleet agent policies:")
            for item in policies:
                print(f"  {item.get('id')}: {item.get('name')}")
            selected = _prompt("Fleet agent policy ID")
            if selected in policy_ids:
                return selected
        choices = ", ".join(f"{key} ({value})" for key, value in policy_ids.items())
        raise OnboardingError(
            "unable to identify the enrolled local Elastic Agent policy; set "
            f"FLEET_AGENT_POLICY_ID to one of: {choices or 'no policies returned'}"
        )

    def ensure_endpoint(self, policy_id: str) -> tuple[str, bool]:
        policies = self.request("/api/fleet/package_policies?perPage=100&format=legacy").get("items", [])
        for item in policies:
            attached = set(item.get("policy_ids") or [item.get("policy_id")])
            if item.get("package", {}).get("name") == "endpoint" and policy_id in attached:
                return str(item["id"]), False
        package = self.request("/api/fleet/epm/packages/endpoint").get("item", {})
        version = str(package.get("version") or package.get("latestVersion") or "")
        if not version:
            raise OnboardingError("Kibana did not return an Elastic Defend package version")
        created = self.request(
            "/api/fleet/package_policies",
            method="POST",
            body={
                "name": "WatchMyAI data collection",
                "description": "File-event collection for WatchMyAI WMAI-023 and WMAI-024 validation",
                "namespace": "default",
                "policy_ids": [policy_id],
                "enabled": True,
                "inputs": [
                    {
                        "enabled": True,
                        "streams": [],
                        "type": "ENDPOINT_INTEGRATION_CONFIG",
                        "config": {
                            "_config": {
                                "value": {
                                    "type": "endpoint",
                                    "endpointConfig": {"preset": "DataCollection"},
                                }
                            }
                        },
                    }
                ],
                "package": {"name": "endpoint", "title": "Elastic Defend", "version": version},
            },
        )
        identifier = str(created.get("item", {}).get("id", ""))
        if not identifier:
            raise OnboardingError("Elastic Defend package policy creation returned no ID")
        return identifier, True

    def verify_policy(self, policy_id: str, *, wait_seconds: int = 120) -> str:
        policies = self.request("/api/fleet/package_policies?perPage=100&format=legacy").get("items", [])
        endpoint = any(
            item.get("package", {}).get("name") == "endpoint"
            and policy_id in set(item.get("policy_ids") or [item.get("policy_id")])
            for item in policies
        )
        if not endpoint:
            raise OnboardingError(f"Fleet policy {policy_id} has no Elastic Defend integration")
        agent_policies = self.request("/api/fleet/agent_policies?perPage=100").get("items", [])
        selected = next((item for item in agent_policies if str(item.get("id")) == policy_id), None)
        if selected is None:
            raise OnboardingError(f"Fleet policy disappeared during verification: {policy_id}")
        expected_revision = int(selected.get("revision", 0))
        deadline = time.monotonic() + wait_seconds
        while True:
            agents = self.request("/api/fleet/agents?perPage=100&showInactive=false").get("items", [])
            current = [
                agent
                for agent in agents
                if str(agent.get("policy_id")) == policy_id
                and str(agent.get("status", "")).lower() in {"online", "healthy"}
                and int(agent.get("policy_revision") or 0) >= expected_revision
            ]
            if current:
                return (
                    f"Fleet policy {policy_id}: {len(current)} online agent(s) acknowledged "
                    f"revision {expected_revision}; Elastic Defend installed"
                )
            if time.monotonic() >= deadline:
                raise OnboardingError(
                    f"Fleet policy {policy_id} has no online agent acknowledging revision "
                    f"{expected_revision}; check Agent policy/application status"
                )
            time.sleep(5)


def _save_setup_state(home: Path, state: dict[str, Any]) -> None:
    _write_private(home / "setup-state.json", json.dumps(state, indent=2, sort_keys=True) + "\n")


def _initialize_gateway(root: Path, home: Path, values: dict[str, str], args: Any) -> None:
    environment = _environment(values)
    init = _run(
        [sys.executable, "-m", "watchmyai.cli.main", "--home", str(home), "init"],
        cwd=root,
        env=environment,
    )
    _require(init, code=EXIT_VALIDATION)
    _configure_gateway(
        home,
        values,
        development=args.development,
        repository_only=args.repository_only,
    )
    if not args.development:
        if not args.signed_root or not args.signed_policy_release or not args.organization_id:
            raise OnboardingError(
                "signed setup requires --signed-root, --signed-policy-release, and --organization-id"
            )
        trusted = home / "distribution" / "trusted-root.json"
        if not trusted.exists():
            enroll = _run(
                [
                    sys.executable,
                    "-m",
                    "watchmyai.cli.main",
                    "--home",
                    str(home),
                    "policy",
                    "enroll-root",
                    str(args.signed_root),
                    "--organization-id",
                    args.organization_id,
                ],
                cwd=root,
                env=environment,
            )
            _require(enroll, code=EXIT_VALIDATION)
        activate = _run(
            [
                sys.executable,
                "-m",
                "watchmyai.cli.main",
                "--home",
                str(home),
                "policy",
                "activate",
                str(args.signed_policy_release),
            ],
            cwd=root,
            env=environment,
        )
        _require(activate, code=EXIT_VALIDATION)


def setup(args: Any) -> int:
    root = repository_root()
    if args.repository_only:
        home = Path(args.home or (Path.cwd() / ".watchmyai-ci-home")).expanduser().resolve()
        values = {
            "WATCHMYAI_HOME": str(home),
            "WATCHMYAI_TEST_WORKSPACE": str(home / "validation-workspace"),
            "WATCHMYAI_POLICY_MODE": "development",
        }
        Path(values["WATCHMYAI_TEST_WORKSPACE"]).mkdir(mode=0o700, parents=True, exist_ok=True)
        args.development = True
        _initialize_gateway(root, home, values, args)
        check = _run(
            [
                sys.executable,
                "-m",
                "watchmyai.cli.main",
                "--home",
                str(home),
                "self-check",
            ],
            cwd=root,
            env={**os.environ, "WATCHMYAI_ALLOW_UNSIGNED_POLICY": "1"},
        )
        _require(check, code=EXIT_VALIDATION)
        _save_setup_state(
            home,
            {
                "installed_hooks": [],
                "policy_mode": "development",
                "repository_only": True,
            },
        )
        print("\nPASS: repository-only setup completed")
        return 0

    if not args.development and (
        not args.signed_root or not args.signed_policy_release or not args.organization_id
    ):
        raise OnboardingError(
            "choose --development or provide --signed-root, --signed-policy-release, and --organization-id",
            exit_code=EXIT_CONFIGURATION,
        )
    if not args.development and args.enable_rules is not True:
        raise OnboardingError(
            "signed setup requires --enable-rules so final verification can prove a current alert",
            exit_code=EXIT_CONFIGURATION,
        )

    config_path, values = _collect_configuration(args, root)
    fleet = FleetClient(values)
    policy_id = fleet.select_policy(
        values.get("FLEET_AGENT_POLICY_ID", ""), interactive=not args.non_interactive
    )
    values["FLEET_AGENT_POLICY_ID"] = policy_id
    _write_config(config_path, _read_env(root / ".env.example"), values)
    environment = _environment(values)
    config_check = _run(
        [
            sys.executable,
            str(root / "scripts/validate/validate_config.py"),
            "--config",
            str(config_path),
        ],
        cwd=root,
        env=environment,
    )
    _require(config_check, code=EXIT_CONFIGURATION)
    repository_check = _run(
        [
            sys.executable,
            str(root / "scripts/preflight.py"),
            "--repository-only",
            *(["--allow-dirty"] if args.allow_dirty else []),
        ],
        cwd=root,
        env=environment,
    )
    _require(repository_check, code=EXIT_VALIDATION)
    home = Path(values["WATCHMYAI_HOME"])
    _initialize_gateway(root, home, values, args)

    assets = _run(
        [
            "bash",
            str(root / "telemetry-gateway/deployment/elastic/load-assets.sh"),
            "--config",
            str(config_path),
        ],
        cwd=root,
        env=environment,
    )
    _require(assets, code=EXIT_CONNECTIVITY)

    package_policy_id, created = fleet.ensure_endpoint(policy_id)
    print(f"[PASS] Fleet policy: {fleet.verify_policy(policy_id)}")

    imported = _run(
        [
            sys.executable,
            str(root / "scripts/import/import_rules.py"),
            "--config",
            str(config_path),
        ],
        cwd=root,
        env=_environment(values),
    )
    _require(imported, code=EXIT_RULE_IMPORT)

    installed_hooks: list[str] = []
    targets = args.hooks
    if targets == "auto":
        targets = "all"
    for target, detected in (
        ("claude", bool(os.environ.get("CLAUDE_SETTINGS_PATH") or Path.home().joinpath(".claude").exists())),
        ("codex", bool(os.environ.get("CODEX_HOME") or Path.home().joinpath(".codex").exists())),
    ):
        if targets not in {"all", target} or (args.hooks == "auto" and not detected):
            continue
        installed = _run(
            [
                sys.executable,
                "-m",
                "watchmyai.cli.main",
                "--home",
                str(home),
                "install",
                target,
            ],
            cwd=root,
            env=_environment(values),
        )
        _require(installed, code=EXIT_VALIDATION)
        installed_hooks.append(target)

    _save_setup_state(
        home,
        {
            "config": str(config_path),
            "fleet_agent_policy_id": policy_id,
            "endpoint_package_policy_id": package_policy_id,
            "endpoint_package_policy_created": created,
            "installed_hooks": installed_hooks,
            "policy_mode": values["WATCHMYAI_POLICY_MODE"],
        },
    )
    verify_args = type(
        "VerifyArgs",
        (),
        {
            "config": str(config_path),
            "repository_only": False,
            "allow_dirty": args.allow_dirty,
            "home": str(home),
        },
    )()
    if verify(verify_args):
        raise OnboardingError("final verification failed")
    print("\nPASS: WatchMyAI setup completed; run 'watchmyai validate' to generate all 20 alerts")
    return 0


def _emit_verification_event(root: Path, home: Path) -> tuple[str, str]:
    run_id = "watchmyai-verify-" + uuid.uuid4().hex
    session_id = "session-" + run_id
    started_at = datetime.now(UTC)
    fixture = json.loads((root / "detection-rules/tests/fixtures/malicious/WMAI-001.json").read_text("utf-8"))
    event = fixture["events"][0]
    event["@timestamp"] = started_at.isoformat(timespec="milliseconds").replace("+00:00", "Z")
    event["event"]["id"] = run_id + "-event-000"
    watchmyai = event["watchmyai"]
    watchmyai["session"]["id"] = session_id
    watchmyai["action"]["id"] = run_id + "-action-000"
    watchmyai.setdefault("context", {}).update(
        {
            "validation_run_id": run_id,
            "scenario_id": "SCN-VERIFY-WMAI-001",
            "rule_id": "WMAI-001",
        }
    )
    gateway = Gateway(GatewayConfig.load(home))
    emitted = gateway.emit(event)
    gateway.flush()
    if emitted is None:
        raise OnboardingError("gateway rejected the controlled verification event")
    return session_id, started_at.isoformat()


def _verify_expected_alert(
    root: Path,
    values: dict[str, str],
    *,
    session_id: str,
    started_at: str,
) -> str:
    scripts_path = str(root / "scripts")
    if scripts_path not in sys.path:
        sys.path.insert(0, scripts_path)
    from validate.run_supported_rules import verify_current_alert

    return verify_current_alert(
        values,
        rule_id="WMAI-001",
        run_id=session_id.removeprefix("session-"),
        session_id=session_id,
        started_at=started_at,
    )


def verify(args: Any) -> int:
    root = repository_root()
    if args.repository_only:
        command = [
            sys.executable,
            str(root / "scripts/preflight.py"),
            "--repository-only",
            *(["--allow-dirty"] if args.allow_dirty else []),
        ]
        stage = _run(command, cwd=root)
        if stage.detail:
            print(stage.detail)
        print("PASS" if stage.status == "PASS" else "FAIL")
        return 0 if stage.status == "PASS" else EXIT_VALIDATION

    config_path = Path(args.config).expanduser().resolve()
    if not config_path.is_file():
        print(f"FAIL: configuration file not found: {config_path}", file=sys.stderr)
        return EXIT_CONFIGURATION
    values = _read_env(config_path)
    home = Path(args.home or values["WATCHMYAI_HOME"]).expanduser().resolve()
    try:
        session_id, started_at = _emit_verification_event(root, home)
        print(f"[PASS] gateway emitted controlled WMAI-001 telemetry session {session_id}")
        fleet_detail = FleetClient(values).verify_policy(values["FLEET_AGENT_POLICY_ID"])
        print(f"[PASS] {fleet_detail}")
    except (KeyError, OSError, OnboardingError, RuntimeError, ValueError) as exc:
        print(f"[FAIL] telemetry/Fleet verification: {exc}", file=sys.stderr)
        print("FAIL")
        return EXIT_VALIDATION
    command = [
        sys.executable,
        str(root / "scripts/preflight.py"),
        "--config",
        str(config_path),
        *(["--allow-dirty"] if args.allow_dirty else []),
    ]
    verification_environment = _environment(values)
    verification_environment["WATCHMYAI_VERIFY_SESSION_ID"] = session_id
    stage = _run(command, cwd=root, env=verification_environment, timeout=1200)
    if stage.detail:
        print(stage.detail)
    if stage.status != "PASS":
        print("FAIL")
        return EXIT_VALIDATION
    try:
        alert_id = _verify_expected_alert(
            root,
            values,
            session_id=session_id,
            started_at=started_at,
        )
    except (KeyError, OSError, OnboardingError, RuntimeError, ValueError) as exc:
        print(f"[FAIL] expected-alert verification: {exc}", file=sys.stderr)
        print("FAIL")
        return EXIT_VALIDATION
    print(f"[PASS] WMAI-001 current-run alert correlated: {alert_id}")
    print("PASS")
    return 0


def validate(args: Any) -> int:
    root = repository_root()
    config = Path(args.config).expanduser().resolve()
    command = [
        sys.executable,
        str(root / "scripts/validate/run_supported_rules.py"),
        "--config",
        str(config),
    ]
    if not args.static_only:
        command.append("--live")
    if args.output:
        command.extend(["--output", str(Path(args.output).expanduser().resolve())])
    values = _read_env(config) if config.is_file() else {}
    completed = subprocess.run(command, cwd=root, env=_environment(values), check=False)
    print("PASS" if completed.returncode == 0 else "FAIL")
    return completed.returncode


def _safe_runtime_home(path: Path, root: Path) -> None:
    resolved = path.expanduser().resolve()
    forbidden = {Path("/"), Path.home().resolve(), root.resolve(), root.resolve().parent}
    if resolved in forbidden or resolved.is_relative_to(root.resolve()):
        raise OnboardingError(f"refusing unsafe runtime removal target: {resolved}")


def uninstall(args: Any) -> int:
    root = repository_root()
    config_path = Path(args.config).expanduser().resolve()
    values = _read_env(config_path) if config_path.is_file() else {}
    home = Path(args.home or values.get("WATCHMYAI_HOME") or GatewayConfig.load().home).resolve()
    if not args.yes:
        print("Re-run with --yes after reviewing the uninstall scope.", file=sys.stderr)
        return 2
    failures: list[str] = []
    environment = _environment({**values, "ENABLE_RULES": "false"})
    if config_path.is_file():
        disabled = _run(
            [
                sys.executable,
                str(root / "scripts/import/import_rules.py"),
                "--config",
                str(config_path),
            ],
            cwd=root,
            env=environment,
        )
        if disabled.status != "PASS":
            failures.append("rule disablement: " + disabled.detail)
        else:
            print("[PASS] 20 WatchMyAI rules disabled")
    state_path = home / "setup-state.json"
    installed_hooks: tuple[str, ...] = ("claude", "codex")
    if state_path.is_file():
        try:
            state = json.loads(state_path.read_text("utf-8"))
            recorded = state.get("installed_hooks", [])
            if not isinstance(recorded, list) or not all(item in {"claude", "codex"} for item in recorded):
                raise ValueError("installed_hooks must contain only claude or codex")
            installed_hooks = tuple(dict.fromkeys(recorded))
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            failures.append(f"setup state: {exc}")
            installed_hooks = ()
    for target in installed_hooks:
        removed = _run(
            [
                sys.executable,
                "-m",
                "watchmyai.cli.main",
                "--home",
                str(home),
                "uninstall",
                target,
            ],
            cwd=root,
            env=environment,
        )
        if removed.status != "PASS":
            failures.append(f"{target} hooks: {removed.detail}")
        else:
            print(f"[PASS] {target} hooks removed")
    if not installed_hooks and not failures:
        print("[PASS] no setup-managed hooks were recorded")
    if args.purge_runtime:
        try:
            _safe_runtime_home(home, root)
            import shutil

            shutil.rmtree(home)
            print(f"[PASS] removed runtime home {home}; this is not recoverable")
        except (OSError, OnboardingError) as exc:
            failures.append(f"runtime removal: {exc}")
    else:
        print(f"[PASS] runtime evidence preserved at {home}")
    if failures:
        for failure in failures:
            print(f"[FAIL] {failure}", file=sys.stderr)
        print("FAIL")
        return EXIT_VALIDATION
    print("PASS")
    return 0
